"""Diet and allergen keyword maps for Stage 1 filtering.

These lists will drive hard-constraint checks in later steps.
Ingredient matching uses normalized substring checks against parsed
ingredient text (Step 2 parser).
"""

SUPPORTED_DIETS = ("vegetarian", "vegan")

SUPPORTED_ALLERGENS = ("nuts", "dairy", "gluten")

# Animal products blocked for vegetarian/vegan diets.
MEAT_KEYWORDS = (
    "chicken",
    "beef",
    "pork",
    "lamb",
    "turkey",
    "bacon",
    "ham",
    "sausage",
    "prosciutto",
    "pepperoni",
    "salami",
    "steak",
    "veal",
    "duck",
    "venison",
    "chorizo",
    "meat",
    "ground beef",
    "ground pork",
    "ground turkey",
)

FISH_KEYWORDS = (
    "fish",
    "salmon",
    "tuna",
    "cod",
    "shrimp",
    "prawn",
    "crab",
    "lobster",
    "scallop",
    "mussel",
    "clam",
    "oyster",
    "anchovy",
    "sardine",
    "trout",
    "halibut",
    "tilapia",
    "mahi",
    "catfish",
    "seafood",
)

# Extra blocks for vegan (vegetarian allows dairy/eggs).
ANIMAL_DERIVED_KEYWORDS = (
    "milk",
    "butter",
    "cream",
    "cheese",
    "yogurt",
    "yoghurt",
    "egg",
    "eggs",
    "honey",
    "gelatin",
    "whey",
    "casein",
    "ghee",
    "buttermilk",
    "sour cream",
    "cream cheese",
    "parmesan",
    "mozzarella",
    "cheddar",
    "mayonnaise",
)

ALLERGEN_KEYWORDS = {
    "nuts": (
        "almond",
        "walnut",
        "pecan",
        "cashew",
        "pistachio",
        "hazelnut",
        "macadamia",
        "peanut",
        "pine nut",
        "brazil nut",
        "nut",
    ),
    "dairy": (
        "milk",
        "butter",
        "cream",
        "cheese",
        "yogurt",
        "yoghurt",
        "whey",
        "casein",
        "ghee",
        "buttermilk",
        "sour cream",
        "cream cheese",
        "parmesan",
        "mozzarella",
        "cheddar",
        "lactose",
    ),
    "gluten": (
        "wheat",
        "barley",
        "rye",
        "flour",
        "bread",
        "pasta",
        "noodle",
        "semolina",
        "bulgur",
        "couscous",
        "seitan",
        "spelt",
        "farro",
        "malt",
        "soy sauce",
        "breadcrumbs",
        "crouton",
        "tortilla",
        "pita",
        "bagel",
        "bun",
        "roll",
        "dough",
        "pastry",
        "cake",
        "cookie",
        "cracker",
    ),
}
